### ISSUE TITLE
Untranslatable strings 

### ISSUE THREAD

**Issue by ghost** [aleiepure/devtoolbox#1]
Hi, @aleiepure 

Your "translate only inside ()" request isn't efficient for some languages. Chinese, Korean, Arabic, Russian ...

Could you mark all these strings translatable.

```
                                  <!-- TRANSLATORS: translate only inside () -->
                                  <item translatable="yes">Version-1 (MAC address)</item>
                                  <item>Version-3</item>
                                  <!-- TRANSLATORS: translate only inside () -->
                                  <item translatable="yes">Version-4 (Random)</item>
                                  <item>Version-5</item>
                                  <!-- TRANSLATORS: translate only inside () -->
                                  <item translatable="yes">Version-6 (Gregorian Time)</item>
                                  <!-- TRANSLATORS: translate only inside () -->
                                  <item translatable="yes">Version-7 (UNIX Epoch)</item>

```

Source: https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/uuid_generator.ui#L52

**Comment by ghost** [comment]
For the same reason, could you also mark these strings translatable.

```

                                  <item translatable="yes">Original</item>
                                  <item>Sentence case</item>
                                  <item>lower case</item>
                                  <item>UPPER CASE</item>
                                  <item>Title Case</item>
                                  <item>camelCase</item>
                                  <item>PascalCase</item>
                                  <item>snake_case</item>
                                  <item>CONSTANT_CASE</item>
                                  <item>kebab-case</item>
                                  <item>COBOL-CASE</item>
                                  <item>Train-Case</item>
                                  <item>aLtErNaTiNg CaSe</item>
                                  <item>ReVeRsE aLtErNaTiNg CaSe</item>
```

Source: https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/text_inspector.ui#L55-L67

**Comment by ghost** [comment]
Sorry, another examples:

```
                                <property name="label">Lorem ipsum dolor sit amet</property>
                                <property name="label">velit laboris excepteur aliqua nostrud dolore anim ad qui esse</property>
```

Source: 
- https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/contrast_checker.ui#L113
- https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/contrast_checker.ui#L113

**Comment by aleiepure** [comment]
> Hi, @aleiepure
> 
> Your "translate only inside ()" request isn't efficient for some languages. Chinese, Korean, Arabic, Russian ...
> 
> Could you mark all these strings translatable.
> 
> ```
>                                   
>                                   <item translatable="yes">Version-1 (MAC address)</item>
>                                   <item>Version-3</item>
>                                   
>                                   <item translatable="yes">Version-4 (Random)</item>
>                                   <item>Version-5</item>
>                                   
>                                   <item translatable="yes">Version-6 (Gregorian Time)</item>
>                                   
>                                   <item translatable="yes">Version-7 (UNIX Epoch)</item>
> ```
> 
> Source: https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/uuid_generator.ui#L52

I'm used to thinking of Latin languages and the parenthesis problem didn't cross my mind. Fixed in bad6425

> For the same reason, could you also mark these strings translatable.
> 
> ```
> 
>                                   <item translatable="yes">Original</item>
>                                   <item>Sentence case</item>
>                                   <item>lower case</item>
>                                   <item>UPPER CASE</item>
>                                   <item>Title Case</item>
>                                   <item>camelCase</item>
>                                   <item>PascalCase</item>
>                                   <item>snake_case</item>
>                                   <item>CONSTANT_CASE</item>
>                                   <item>kebab-case</item>
>                                   <item>COBOL-CASE</item>
>                                   <item>Train-Case</item>
>                                   <item>aLtErNaTiNg CaSe</item>
>                                   <item>ReVeRsE aLtErNaTiNg CaSe</item>
> ```
> 
> Source: https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/text_inspector.ui#L55-L67

They are intended as a reference and IMO they should be translated into any language.




> Sorry, another examples:
> 
> ```
>                                 <property name="label">Lorem ipsum dolor sit amet</property>
>                                 <property name="label">velit laboris excepteur aliqua nostrud dolore anim ad qui esse</property>
> ```
> 
> Source:
> 
>     * https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/contrast_checker.ui#L113
> 
>     * https://github.com/aleiepure/devtoolbox/blob/main/src/ui/views/contrast_checker.ui#L113

Same as above, usually lorem ipsum texts stay in Latin regardless of the destination language.

**Comment by ghost** [comment]
I thought you are going to mark them translatable. 

> "usually lorem ipsum texts stay in Latin regardless of the destination language."

Usually but is not efficient for non Latin languages. In the end, it's up to developer.

**Comment by aleiepure** [comment]
For now, I'm closing this. If someone else in the future will raise this issue again I'll think about it.
