### ISSUE TITLE
webkit2gtk-5.0 is now webkitgtk-6.0

### ISSUE THREAD

**Issue by yochananmarqos** [aleiepure/devtoolbox#13]
Just FYI: https://discourse.gnome.org/t/webkitgtk-for-gtk-4-is-now-api-stable/14378

**Comment by yochananmarqos** [comment]
More news: https://blogs.gnome.org/mcatanzaro/2023/03/21/webkitgtk-api-for-gtk-4-is-now-stable/

**Comment by aleiepure** [comment]
Fixed in 4da75ee.
