### ISSUE TITLE
Allow smaller window size

### ISSUE THREAD

**Issue by Tentacular261** [aleiepure/devtoolbox#15]
**Describe the issue**
I have a 1080p monitor oriented vertically. When I open devtoolbox on it, part of the window overflows to my other monitor.

**To Reproduce**
1. Open app on 1080p monitor.
2. Try to Resize to 1080 pixels wide.
3. Notice that it won't go that narrow; only goes to approximately 1200 pixels

**Expected behavior**
It should be able to size to at least 1080 pixels wide.

**Screenshots**
The red line is where the 1080 pixel mark is:

![image](https://user-images.githubusercontent.com/12791325/223777807-ad7b1fa4-45ab-4edc-a413-7eca3cb9eed9.png)

**Operating system (please complete the following information):**
 - Distro: Pop!_OS
 - Version: 22.04 LTS
 - Desktop Environment: Gnome 42.5
 - Xorg/Wayland: Xorg

**Comment by ghost** [comment]
I agree, it would be nice to be able to shrink the window a bit further than what's currently possible.

**Comment by aleiepure** [comment]
You are right, it should be able to shrink more. During development, the layout for some tools at sizes smaller than 1200 wasn't right, but now it's no longer the case. Consider it fixed for the next version.

**Comment by aleiepure** [comment]
Fixed in 771afae
