### ISSUE TITLE
System colour scheme is not followed.

### ISSUE THREAD

**Issue by AbrarSL** [aleiepure/devtoolbox#21]
The system colour scheme is not followed. I noticed in the code that you've forced the dark mode. Is there a reason for this?

**Comment by aleiepure** [comment]
I had some issues with the light high-contrast theme and I forced the dark mode as a workaround. I use the dark-mode for the OS and I forgot it was there. Thanks for reminding me. Theme switching will be available in the next version.

**Comment by aleiepure** [comment]
Added in a7a530b and soon in the next version.
