### ISSUE TITLE
Add translator-credits

### ISSUE THREAD

**Issue by ghost** [aleiepure/devtoolbox#3]
Hi, I couldn't find any area to add my name as a translator.

Could you add translator-credits?

More information: https://wiki.gnome.org/TranslationProject/DevGuidelines/Add%20translator%20credits

**Comment by aleiepure** [comment]
Translation credits were in place from the beginning, I just forgot to mark them translatable and say in the wiki where to add your name. Now should be fixed in 95e9acb
