### ISSUE TITLE
Does app icon follows Gnome HIG?

### ISSUE THREAD

**Issue by gremo** [aleiepure/devtoolbox#36]
Just out of curiositry, app icon follows the Gnoe HIG as stated [here](https://developer.gnome.org/hig/guidelines/app-icons.html)? I really appreciated the app and I thank you for that! The only think I don't like it's the so complex icon , really, take it as a compliment :+1:

**Comment by aleiepure** [comment]
Hi! When I designed it, I tried to apply everything the HIG said. I agree that it is somewhat complex but this is the best I could do with my skills, after all, I am not an artist 😁.
