### ISSUE TITLE
Doesn't start on Arch

### ISSUE THREAD

**Issue by heldderarbeit** [aleiepure/devtoolbox#42]
I have the exact same issue as https://github.com/aleiepure/devtoolbox/issues/28, I believe because of my timezone (I set "Central European Time" during installation with archinstall. Got the empty window at one of the first starts, now nothing happens on launch at all.

```
Traceback (most recent call last):
  File "/app/share/devtoolbox/devtoolbox/main.py", line 76, in do_activate
    win = DevtoolboxWindow(self.debug, application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/devtoolbox/devtoolbox/window.py", line 84, in __init__
    "child": TimestampView(),
             ^^^^^^^^^^^^^^^
  File "/app/share/devtoolbox/devtoolbox/views/timestamp.py", line 39, in __init__
    self._timezone_dropdown.set_selected(common_timezones.index(tz))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'CET' is not in list
```

App is installed via Flathub (v. 1.1.1)

**Operating system (please complete the following information):**
 - Distro: Arch
 - Desktop Environment: Gnome 46
 - Xorg/Wayland: Wayland

**Comment by aleiepure** [comment]
Hi! The issue is now fixed in [#5e9c384](https://github.com/aleiepure/devtoolbox/commit/5e9c384c1fc4e53c67356f7a7bdc006ad9f4c586).
Sorry it took me so long to fix this
