### ISSUE TITLE
Let XML formatter open .ui files

### ISSUE THREAD

**Issue by ghost** [aleiepure/devtoolbox#6]
**Is your feature request related to a problem? Please describe.**
A lot of GNOME apps use `.ui` files, for instance `window.ui`. However, right now, one can only open `.xml` files with the XML formatter.

**Describe the solution you'd like**
`.ui` files should be among the accepted file types in the file picker for the XML formatter.

**Describe alternatives you've considered**
*None*

**Additional context**
*None*

**Comment by ghost** [comment]
Funnily enough, Dev Toolbox itself uses `.ui` files.

**Comment by aleiepure** [comment]
You are 100% right. fixed in 946c08c
