### ISSUE TITLE
Windows support.

### ISSUE THREAD

**Issue by CodeCubeNeo** [aleiepure/devtoolbox#9]
Is it possible to build a windows exe/msi out of this?

**Comment by aleiepure** [comment]
It should be possible but I don't have any Windows system to test on. Targeting multiple OSes is no small task and this is meant as a linux only program. For other OSes there are very similar alternatives like devtoys for windows and devutils for macOS. 
If someone else is willing to take this task I'm available to collaborate with but it's not something that I'm going to tackle by myself.
